### ISSUE TITLE
Typo in common/start-taky-certgen.sh

### ISSUE THREAD

**Issue by sgofferj** [skadakar/taky-docker#2]
Line 5
`chomd -x /common/hackofthecert.py`
Should probably be
`chmod -x /common/hackofthecert.py`

**Comment by sgofferj** [comment]
I get also
`/common/start-taky-certgen.sh: line 12: syntax error: unexpected end of file`

**Comment by skadakar** [comment]
Good find, fixed now, should be in dockerhub somewhat shortly.

**Comment by skadakar** [comment]
Change is in latest now.
