### ISSUE TITLE
Container starts redis server when redis URL is given

### ISSUE THREAD

**Issue by sgofferj** [skadakar/taky-docker#3]
When a redis url is given in the preferences, the container still starts a redis server inside itself. The taky server connects to the given URL, though.

**Comment by skadakar** [comment]
Is it propagated correctly into the taky config file?

**Comment by sgofferj** [comment]
Jep... /data/conf/taky.conf
`redis=redis://redis:6379`

**Comment by skadakar** [comment]
Completely ignored this, added a really half-assed check now. If you could verify that'd be greatt.

**Comment by sgofferj** [comment]
Seems to work. At least, TAKY says it connects to the URL and doesn't complain. Your script seems to complain, though

```
/common/start-taky-cot.sh: line 25: redis://redis:6379: No such file or directory
Redis not True and not empty, assuming connection string.
```
