### ISSUE TITLE
link /etc/taky/ssl to /data/ssl

### ISSUE THREAD

**Issue by sgofferj** [skadakar/taky-docker#4]
The cert gen procedure copies the certificates to /data/ssl for persistence. takyctl build_client, however, expects the server certificate in /etc/taky/ssl and thus fails when run inside the container.
Either the directories suld be linked or the container init script should copy the certs from /data/ssl to /etc/ssl so takyctl build_client works.

**Comment by skadakar** [comment]
Linking is preferable I think, if you submit a PR I'll accept push it.

**Comment by sgofferj** [comment]
Have to see if I still have space for yet another git repo on my PC :rofl:

**Comment by sgofferj** [comment]
Actually, I just figured that takyctl should be called with the configfile as parameter. When doing that, it will find the certs in /data/ssl. Closing. Apologies for the oversight.
